# -*- coding: utf-8 -*-
"""엑셀에서 단어 카운팅.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USHr5J7riozkhWYv8DFLMIwFIoEsgOQA
"""

import pandas as pd
import numpy as np
from openpyxl import load_workbook

bag_of_words = []
frequency = []


load_wb =load_workbook('LibertyKorea_north1.xlsx',data_only=True)
load_ws=load_wb['Sheet']
for i in range(1,700):
  for j in range(1000):
    word = load_ws.cell(i+1,j+1).value
    if word not in bag_of_words:
      bag_of_words.append(word)
      frequency.append(1)
    else:
      frequency[bag_of_words.index(word)] = frequency[bag_of_words.index(word)]+1
      
load_wb =load_workbook('LibertyKorea_policy1.xlsx',data_only=True)
load_ws=load_wb['Sheet']
for i in range(1,185):
  for j in range(1000):
    word = load_ws.cell(i+1,j+1).value
    if word not in bag_of_words:
      bag_of_words.append(word)
      frequency.append(1)
    else:
      frequency[bag_of_words.index(word)] = frequency[bag_of_words.index(word)]+1

load_wb =load_workbook('LibertyKorea_kim1.xlsx',data_only=True)
load_ws=load_wb['Sheet']
for i in range(1,185):
  for j in range(1000):
    word = load_ws.cell(i+1,j+1).value
    if word not in bag_of_words:
      bag_of_words.append(word)
      frequency.append(1)
    else:
      frequency[bag_of_words.index(word)] = frequency[bag_of_words.index(word)]+1


bagofword = {"Word":bag_of_words, "Frequency" : frequency}
result = pd.DataFrame(bagofword)
result.to_excel("bagofwords_liberty.xlsx",index = False)